#ifndef LISTENUMS_H_INCLUDED
#define LISTENUMS_H_INCLUDED

enum TREATEMENT_TYPE
{
    ID_FILTRE_NONE = 0,
    ID_FILTRE_GAUSSIEN,
    ID_FILTRE_MEDIAN,
    ID_FILTRE_CANNY,
    ID_FILTRE_CONV_MOYENNEUR,
    ID_FILTRE_CONV_SHARPEN,
    ID_FILTRE_CONV_LAPLACIEN,
    ID_FILTRE_CONV_SOBEL_X,
    ID_FILTRE_CONV_SOBEL_Y,
    ID_FILTRE_SEUILLAGE,
    ID_FILTRE_EROSION,
    ID_FILTRE_DILATATION,
    ID_FILTRE_OUVERTURE,
    ID_FILTRE_FERMETURE
};


#endif