name: Build C++ project with TDM-GCC, wxWidgets and OpenCV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:    
  build:
    runs-on: windows-latest
  
    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
  
    # 2. Install TDM-GCC-64 (GCC for Windows)
    - name: Install TDM-GCC-64 manually
      run: |
        curl -L -o tdm-gcc-64.exe https://jmeubank.github.io/tdm-gcc/download/tdm64-gcc-10.3.0.exe
        start /wait tdm-gcc-64.exe /S
        setx PATH "%PATH%;C:\TDM-GCC-64\bin"
      shell: cmd
  
    # 3. Install vcpkg (for wxWidgets and OpenCV)
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install wxwidgets:x64-windows
        .\vcpkg\vcpkg install opencv:x64-windows
      shell: powershell
  
    # 4. Build the project using g++
    - name: Build the project
      run: |
        g++ -o bin/App.exe src/App.cpp src/Model/*.cpp src/ViewModel/*.cpp src/View/*.cpp ^
        -I C:/path_to_vcpkg/vcpkg/installed/x64-windows/include ^
        -L C:/path_to_vcpkg/vcpkg/installed/x64-windows/lib ^
        -lopencv_world455 -lwxmsw30u_core -lwxbase30u
      shell: cmd
  
    # 5. Upload executable (Optional, if you want to download the binary from the GitHub interface)
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: bin/App.exe
